var Projects = React.createClass({
  render: function() {
    return (
      <div id="projects">
        <Project title="Game the Progress" description="I designed and built Game the Progress, which is a web app created to give teachers a platform to custom build and play game quizzes with multiple students. I worked with a team of four other developers over an eight day period to go from initial pitch to functional product. I worked primarily on the backend ActiveRecord associations and Action Cable WebSockets interface. With my team I demoed the app in front of a live audience and it is available to use on Heroku." image="https://media.licdn.com/media-proxy/ext?w=800&h=800&f=n&hash=PsHBYbLmA06UclvJK%2BlANZQAVqc%3D&ora=1%2CaFBCTXdkRmpGL2lvQUFBPQ%2CxAVta9Er0Vinkhwfjw8177yE41y87UNCVordEGXyD3u0qYrdf3Pof8SLebb3uVsTKiUclFZnLvL6STngD8a6Ioq6etxyisXgIY24ZxUBbFImi24" github="https://github.com/domlet/game_the_progress" liveApp="http://gametheprogress.herokuapp.com/" liveAppName="Heroku App" />
        <Project title="My Linguistic Facts" description="I created and published a skill for the Amazon Alexa skills store. This skill allows Alexa to dynamically respond to requests for information about linguistics. It allows Alexa to respond with a variety of different facts about linguistics spanning many sub-fields including syntax, phonology, morphology, semantics, historical linguistics, language acquisition, and constructed languages. The skill was created using Javascript." image="https://media.licdn.com/media-proxy/ext?w=800&h=800&f=n&hash=NKqpjVNrkxdJMA%2ByLgrxnz%2ByyZY%3D&ora=1%2CaFBCTXdkRmpGL2lvQUFBPQ%2CxAVta9Er0Vinkhwfjw8177yE41y87UNCVordEGXyD3u0qYrdf3Ppf5WJK-OnuQ8SKS4clAdgLfL5FWK3D5vvKI7re9gnjpbtco24ZxUBbFImi24" github="https://github.com/domlet/game_the_progress" liveApp="http://gametheprogress.herokuapp.com/" liveAppName="Alexa Skill"/>
        <Project title="My Gender Identity Facts" description="games yay  lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum" image="https://s-media-cache-ak0.pinimg.com/736x/51/a6/a7/51a6a7af68bf9dd792645ceb248ebd68.jpg" github="https://github.com/domlet/game_the_progress" liveApp="http://gametheprogress.herokuapp.com/" liveAppName="Alexa Skill" />
        <Project title="My Hogwarts Sorting Hat" description="games yay  lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum" image="https://s-media-cache-ak0.pinimg.com/736x/51/a6/a7/51a6a7af68bf9dd792645ceb248ebd68.jpg" github="https://github.com/domlet/game_the_progress" liveApp="http://gametheprogress.herokuapp.com/" liveAppName="Alexa Skill" />
        <Project title="Open Source Project..." description="games yay  lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum" image="https://s-media-cache-ak0.pinimg.com/736x/51/a6/a7/51a6a7af68bf9dd792645ceb248ebd68.jpg" github="https://github.com/domlet/game_the_progress" liveApp="http://gametheprogress.herokuapp.com/" liveAppName="Heroku App" />
        <Project title="Ryker's Portfolio" description="I created this portfolio website to showcase my learning process and accomplishments as a developer. The website was created using Rails and React and is hosted on Heroku." image="https://s-media-cache-ak0.pinimg.com/736x/51/a6/a7/51a6a7af68bf9dd792645ceb248ebd68.jpg" github="https://github.com/domlet/game_the_progress" liveApp="http://gametheprogress.herokuapp.com/" liveAppName="Heroku App" />
      </div>
    );
  }
});
