var Projects = React.createClass({
  render: function() {
    return (
      <div id="projects">
        <Project title="Game the Progress" description="games yay lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum" image="https://media.licdn.com/media-proxy/ext?w=800&h=800&f=n&hash=PsHBYbLmA06UclvJK%2BlANZQAVqc%3D&ora=1%2CaFBCTXdkRmpGL2lvQUFBPQ%2CxAVta9Er0Vinkhwfjw8177yE41y87UNCVordEGXyD3u0qYrdf3Pof8SLebb3uVsTKiUclFZnLvL6STngD8a6Ioq6etxyisXgIY24ZxUBbFImi24" github="https://github.com/domlet/game_the_progress" liveApp="http://gametheprogress.herokuapp.com/" liveAppName="Heroku" />
        <Project title="My Linguistics Facts" description="facts yay  lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum" image="https://media.licdn.com/media-proxy/ext?w=800&h=800&f=n&hash=NKqpjVNrkxdJMA%2ByLgrxnz%2ByyZY%3D&ora=1%2CaFBCTXdkRmpGL2lvQUFBPQ%2CxAVta9Er0Vinkhwfjw8177yE41y87UNCVordEGXyD3u0qYrdf3Ppf5WJK-OnuQ8SKS4clAdgLfL5FWK3D5vvKI7re9gnjpbtco24ZxUBbFImi24" github="https://github.com/domlet/game_the_progress" liveApp="http://gametheprogress.herokuapp.com/" liveAppName="Alexa"/>
        <Project title="My Gender Beyond the Binary Facts" description="games yay  lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum" image="https://s-media-cache-ak0.pinimg.com/736x/51/a6/a7/51a6a7af68bf9dd792645ceb248ebd68.jpg" github="https://github.com/domlet/game_the_progress" liveApp="http://gametheprogress.herokuapp.com/" liveAppName="Alexa" />
        <Project title="My Hogwarts Sorting Hat" description="games yay  lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum" image="https://s-media-cache-ak0.pinimg.com/736x/51/a6/a7/51a6a7af68bf9dd792645ceb248ebd68.jpg" github="https://github.com/domlet/game_the_progress" liveApp="http://gametheprogress.herokuapp.com/" liveAppName="Alexa" />
        <Project title="Open Source Project..." description="games yay  lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum" image="https://s-media-cache-ak0.pinimg.com/736x/51/a6/a7/51a6a7af68bf9dd792645ceb248ebd68.jpg" github="https://github.com/domlet/game_the_progress" liveApp="http://gametheprogress.herokuapp.com/" liveAppName="Heroku" />
        <Project title="Ryker's Portfolio" description="games yay  lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum" image="https://s-media-cache-ak0.pinimg.com/736x/51/a6/a7/51a6a7af68bf9dd792645ceb248ebd68.jpg" github="https://github.com/domlet/game_the_progress" liveApp="http://gametheprogress.herokuapp.com/" liveAppName="Heroku" />
      </div>
    );
  }
});
