# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Category.create(title: 'About Me')
Category.create(title: 'Projects')
Category.create(title: 'Teaching')
Category.create(title: 'Publications')
Category.create(title: 'Hobbies')
Category.create(title: 'Contact')

Block.create(header: 'Post 1', image: 'https://upload.wikimedia.org/wikipedia/commons/b/bd/Grey_Cat.jpg', description: 'description 1 lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum', category_id: 1)
Block.create(header: 'Post 2', image: 'https://upload.wikimedia.org/wikipedia/commons/1/15/Greycat.jpg', description: 'description 2 lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum', category_id: 1)
Block.create(header: 'Post 3', image: 'https://c2.staticflickr.com/2/1095/1464676806_82e8099feb_b.jpg', description: 'description 3 lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum', category_id: 1)
Block.create(header: 'Post 4', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR9HS5Ef8GuAAQaKMOdOS4Rw2w3kcQvwU2IGVHv3D5d0Fd5ZkPsrQ', description: 'description 4 lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum', category_id: 2)
Block.create(header: 'Post 5', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_x0YnYJ9Z5on3EBgXNMuV0jm9RZct9vc0oh251oW9g94CGCeG', description: 'description 5 lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum', category_id: 2)
Block.create(header: 'Post 6', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTOG2YXlge1qBxUN0pjRfUSF10ihMLVfdxyhPhrHaN-BPeYPEGu', description: 'description 6 lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum', category_id: 3)
Block.create(header: 'Post 7', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTvpCjAp_JOxwrZi-d2Vm78SXUA3aIrHx_UAnsTi9KHpYBePfFHkA', description: 'description 7 lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum', category_id: 3)
Block.create(header: 'Post 8', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTvpCjAp_JOxwrZi-d2Vm78SXUA3aIrHx_UAnsTi9KHpYBePfFHkA', description: 'description 8 lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum', category_id: 4)
Block.create(header: 'Post 9', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTOG2YXlge1qBxUN0pjRfUSF10ihMLVfdxyhPhrHaN-BPeYPEGu', description: 'description 9 lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum', category_id: 4)
Block.create(header: 'Post 10', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_x0YnYJ9Z5on3EBgXNMuV0jm9RZct9vc0oh251oW9g94CGCeG', description: 'description 10 lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum', category_id: 5)
Block.create(header: 'Post 11', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR9HS5Ef8GuAAQaKMOdOS4Rw2w3kcQvwU2IGVHv3D5d0Fd5ZkPsrQ', description: 'description 11 lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum', category_id: 5)
Block.create(header: 'Post 12', image: 'https://c2.staticflickr.com/2/1095/1464676806_82e8099feb_b.jpg', description: 'description 12 lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum', category_id: 5)
Block.create(header: 'Post 13', image: 'https://upload.wikimedia.org/wikipedia/commons/1/15/Greycat.jpg', description: 'description 13 lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum', category_id: 6)
